name: ðŸž Bug Report
description: Create a bug (i.e. crash) report to help us improve. Use "plextraktsync bug-report" to pre-fill version info and your config.

body:
  - type: markdown
    attributes:
      value: |
        Before you continue reporting the bug, be sure that you are using supported installation method, see

        - https://github.com/Taxel/PlexTraktSync#installation

        You can find latest version from here:
        - https://github.com/Taxel/PlexTraktSync/tags

  - type: checkboxes
    id: readme
    attributes:
      label: Confirmation
      options:
        - label: I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
          required: true
        - label: I have checked if identical issue already exists
          required: true
        - label: I have tried downgrading to find version that can be used as a workaround

  - type: textarea
    id: description
    attributes:
      label: The problem
      description: >
        A description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the behavior
      description: Write the exact command you used to run it, what you did before and after
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      render: text
      label: Error trace / logs
      description: >
        A complete traceback of the error or content of log file.

        This will be automatically formatted into code, so no need for backticks.

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: inspect
    attributes:
      render: text
      label: Inspect of problematic items
      description: >
        Post here `plextraktsync inspect ID` if needed to understand the problem.

  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: Is there an existing workaround for this issue? Did you try downgrading? Try finding version that can be used as a workaround.

  - type: dropdown
    id: install-method
    attributes:
      label: Install method
      description: How did you install PlexTraktSync
      options:
        - pipx
        - docker-compose
        - pip (not supported)
        - git clone (not supported)
        - zip download (not supported)
        - Unraid installation (not supported)
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      render: yaml
      label: Config file contents
      description: >
        Contents of your config file.

        You can copy this from `plextraktsync config` output.
        This textarea will be automatically formatted as yaml text.

  - type: input
    id: version
    attributes:
      label: Version
      description: Run `plextraktsync --version`. Fill exact version, filling "latest" is not acceptable.
      placeholder: eg. 0.15.0
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      description: You can find it from `plextraktsync info`
      placeholder: eg. 3.7.10
    validations:
      required: true

  - type: input
    id: plex
    attributes:
      label: Plex Server Version
      description: You can find it from `plextraktsync info`
      placeholder: eg. 1.32.8.7639
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System and Version
      placeholder: eg. Windows 10, macOS 10.15, Ubuntu 20.04, etc.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Make sure to close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
